name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi, thanks for opening an issue. Please dont forget to add appropriate information and labels in issue"
        pr-message: "Hi, thanks for contributing to the dsa project"
